/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include "tcMenuU8g2.h"

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // defines the app info to the linker.

// Global variables that need exporting

extern U8G2_SSD1306_128X64_NONAME_F_HW_I2C gfx;
extern U8g2GfxMenuConfig gfxConfig;
extern U8g2MenuRenderer renderer;
// extern IoAbstractionRef io8574;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

void CALLBACK_FUNCTION onStartMeasuring(int id);
void CALLBACK_FUNCTION onStartCalibrate4Ph(int id);
void CALLBACK_FUNCTION onStartCalibrate7Ph(int id);
void CALLBACK_FUNCTION onUpdateCalibrationTolerance(int id);
void CALLBACK_FUNCTION onUpdateStableReadingTotal(int id);

extern AnalogMenuItem menuCalibrationTolerance;
extern AnalogMenuItem menuStableReadingTotal;

#endif // MENU_GENERATED_CODE_H
